<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>auth & acl</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet'
          type='text/css'>

    <!-- Scripts -->
    <script type="application/javascript"
            src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
    <script type="application/javascript"
            src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script type="application/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
    <script type="application/javascript" src=""></script>
</head>
<body>
<div class="container">
    <header>
        <h1>AUTH & ACL-access controll limit</h1>
        <p>controller action: autoload</p>
        <p>roles: inherit, dynamic</p>
    </header>
    <hr>
    <div class="content"><?php echo $this->content; ?> </div>
    <hr>
    <footer>
        <div class="row">
            <div class="col-md-2">
                <img id="authorAvatar"
                     src="https://avatars0.githubusercontent.com/u/8801188?v=3&s=460">
            </div>
            <div class="col-md-10">
                <code>@lehoanganh25991</code>
            </div>
        </div>

    </footer>
</div>

</body>
</html>
