<h3><?php var_dump($this->_vars); ?></h3>
<input type="hidden" id="uniAclConfig" value='<?php echo json_encode($this->uniAclConfig); ?>'>
<input type="hidden" id="userActionOnRole" value='<?php echo json_encode($this->userActionOnRole); ?>'>
<!-- CONTROLLER !-->

<div id="controller">CONTROLLER</div>
<script>
    (function($){
        $(document).ready(function(){
            const CONTROLLER_ACTION = "CONTROLLER_ACTION";
            /**
             * READ CONFIG from server
             */
            var uniAclConfig = JSON.parse($("#uniAclConfig").val());
            var userActionOnRole = JSON.parse($("#userActionOnRole").val());
            console.log(uniAclConfig);
            console.log(userActionOnRole);

            /**
             * VIEW on CONTROLLER
             */
            var controllerAction = uniAclConfig[CONTROLLER_ACTION];
            console.log(controllerAction);
            var controllerDiv = $("#controller");
            for(var controller in controllerAction){
                if(controllerAction.hasOwnProperty(controller)){

                    console.log(controller, controllerAction[controller]);
                    var actionArray = controllerAction[controller];
                    for(var i = 0; i < actionArray.length; i++){
                        var checkBox = $("<input type='checkbox'>");
                        checkBox.attr(name, controller + '[]');
                        var value = actionArray[i];
                        checkBox.attr(value, value);
                        controllerDiv.append(checkBox);
                    }

                }
            }
        });
    })(jQuery);
</script>

